//go:build e2e

package e2e

import (
	"fmt"
	"testing"
	"time"
)

// TestMergeTrainRunawayGuardPausesBatch is the e2e proof of ADR-059 D8: when
// every trial in a batch is persistently red and bisection cannot isolate a
// landable subset, the runaway guard fires — stopping further trial creation
// and pausing all Queued members — rather than looping forever.
//
// Construction: four all-poison members on RepoBeta
// (handarbeit/fabrik-test-beta). Each member writes a file under
// e2e/train/entries/ containing "POISON", so the `train-poison-guard` required
// check fails every trial branch — combined and bisection sub-trials alike.
// With cap=6 (FABRIK_MAX_TRAIN_TRIALS_PER_WINDOW in the bed .env) and ~7–10
// trials generated by 4 poison members × bisection rounds, the guard is
// certain to trip before any member lands.
//
// Running on RepoBeta gives the trial counter (keyed "owner/repo") a fully
// independent namespace from the Alpha scenarios, so parallel Alpha runs do
// not consume this test's cap.
//
// Prerequisites: see tests/e2e/README.md prerequisite #18 (Queued column,
// train-poison-guard required check on fabrik-test-beta,
// FABRIK_MAX_TRAIN_TRIALS_PER_WINDOW=6 in the bed .env).
// Skips cleanly if either prerequisite is absent.
//
// NOT t.Parallel(): it deliberately induces a repo-wide fault on RepoBeta
// (fabrik-test-beta), and TestCrossRepoSpawn is the only other scenario that
// drives real work on that same repo — running concurrently would let this
// test's induced fault pause TestCrossRepoSpawn's in-flight child issue as
// collateral damage (exactly what happened in the 0.0.77 validation gate,
// issue #1395). Mirrors the same serialization idiom TestMergeTrainRestartSafety
// already uses (see its doc comment): Go runs non-parallel tests to completion
// before resuming parallel ones, so this test always finishes — guard tripped,
// all 4 members paused — before TestCrossRepoSpawn starts real work. The test
// body and assertions below are unchanged; only the scheduling annotation was
// removed.
//
// Wall-clock: ~10–20 min (~6 trials × 2 required checks ≈ 12 Actions runs).
// Cost: low (no Claude invocations).
func TestMergeTrainRunawayGuardPausesBatch(t *testing.T) {
	env := LoadEnv(t)
	AssertFabrikRunning(t, env)
	requireTrainBed(t, env)
	assertTrainPoisonGuardRequired(t, env, env.RepoBeta)

	const base = "main"
	logStart := LogOffset(t, env)

	// Queue 4 all-poison members. Every trial branch — combined or bisection —
	// will contain at least one POISON file, so train-poison-guard always fails.
	var members [4]int
	for i := 0; i < 4; i++ {
		n := i + 1
		issue, _ := QueueMember(t, env, env.RepoBeta, base,
			fmt.Sprintf("runaway%d", n),
			fmt.Sprintf("e2e/train/entries/runaway-%d.txt", n),
			fmt.Sprintf("POISON — runaway guard e2e member %d\n", n),
		)
		members[i] = issue
		t.Logf("queued poison member #%d (issue #%d)", n, issue)
	}
	t.Logf("all 4 poison members queued on %s; awaiting runaway guard", env.RepoBeta)

	// Wait for the guard to fire — the longest assertion (up to 25 min).
	WaitForLogLine(t, env, fmt.Sprintf("runaway guard fired for %s", env.RepoBeta), logStart, 25*time.Minute)
	t.Logf("runaway guard fired; checking member labels and comments")

	// Labels are applied inside fireRunawayGuard before the log line is written,
	// so by the time WaitForLogLine returns they should already be set. Allow a
	// generous 5-minute window for GitHub API propagation.
	for _, issueNum := range members {
		WaitForIssueLabel(t, env, env.RepoBeta, issueNum, "fabrik:paused", 5*time.Minute)
		WaitForIssueLabel(t, env, env.RepoBeta, issueNum, "fabrik:awaiting-input", 5*time.Minute)
		t.Logf("member #%d has fabrik:paused + fabrik:awaiting-input", issueNum)
	}

	// Assert the alert comment on every member, not just member[0] (#1533): the guard's
	// pause and alert are two independent GitHub calls per member, and before #1533 a
	// member could end up fabrik:paused with no alert comment at all — a race between
	// fireRunawayGuard's three call sites (Hook 1 x2, Hook 2) that only strengthening
	// this assertion to cover all 4 members can catch. A member whose direct alert
	// failed and fell back to the settleRunawayGuardAlertScan retry still needs to see
	// the comment land within this window — the retry runs every poll cycle.
	for _, issueNum := range members {
		WaitForIssueComment(t, env, env.RepoBeta, issueNum, "runaway guard tripped", 5*time.Minute)
		t.Logf("alert comment confirmed on member #%d", issueNum)
	}

	// No member should have reached Done.
	for _, issueNum := range members {
		if st := projectStatus(t, env, env.RepoBeta, issueNum); st == "Done" {
			t.Fatalf("member #%d reached Done — runaway guard did not fire in time", issueNum)
		} else {
			t.Logf("member #%d correctly not landed (status=%q)", issueNum, st)
		}
	}

	WaitForNoStaleTrainArtifacts(t, env, env.RepoBeta, 2*time.Minute)
	t.Logf("runaway guard contract verified: all-poison batch → guard fires at cap → all Queued members paused → no member reaches Done")
}
