//go:build e2e

package e2e

import (
	"fmt"
	"testing"
	"time"
)

// TestMergeTrainRunawayGuardPausesBatch is the e2e proof of ADR-059 D8: when
// every trial in a batch is persistently red and bisection cannot isolate a
// landable subset, the runaway guard fires — stopping further trial creation
// and pausing all Queued members — rather than looping forever.
//
// Construction: four all-poison members on RepoBeta
// (handarbeit/fabrik-test-beta). Each member writes a file under
// e2e/train/entries/ containing "POISON", so the `train-poison-guard` required
// check fails every trial branch — combined and bisection sub-trials alike.
// With cap=6 (FABRIK_MAX_TRAIN_TRIALS_PER_WINDOW in the bed .env) and ~7–10
// trials generated by 4 poison members × bisection rounds, the guard is
// certain to trip before any member lands.
//
// Running on RepoBeta gives the trial counter (keyed "owner/repo") a fully
// independent namespace from the Alpha scenarios, so parallel Alpha runs do
// not consume this test's cap.
//
// Prerequisites: see tests/e2e/README.md prerequisite #18 (Queued column,
// train-poison-guard required check on fabrik-test-beta,
// FABRIK_MAX_TRAIN_TRIALS_PER_WINDOW=6 in the bed .env).
// Skips cleanly if either prerequisite is absent.
//
// Wall-clock: ~10–20 min (~6 trials × 2 required checks ≈ 12 Actions runs).
// Cost: low (no Claude invocations).
func TestMergeTrainRunawayGuardPausesBatch(t *testing.T) {
	t.Parallel()
	env := LoadEnv(t)
	AssertFabrikRunning(t, env)
	requireTrainBed(t, env)
	assertTrainPoisonGuardRequired(t, env, env.RepoBeta)

	const base = "main"
	logStart := LogOffset(t, env)

	// Queue 4 all-poison members. Every trial branch — combined or bisection —
	// will contain at least one POISON file, so train-poison-guard always fails.
	var members [4]int
	for i := 0; i < 4; i++ {
		n := i + 1
		issue, _ := QueueMember(t, env, env.RepoBeta, base,
			fmt.Sprintf("runaway%d", n),
			fmt.Sprintf("e2e/train/entries/runaway-%d.txt", n),
			fmt.Sprintf("POISON — runaway guard e2e member %d\n", n),
		)
		members[i] = issue
		t.Logf("queued poison member #%d (issue #%d)", n, issue)
	}
	t.Logf("all 4 poison members queued on %s; awaiting runaway guard", env.RepoBeta)

	// Wait for the guard to fire — the longest assertion (up to 25 min).
	WaitForLogLine(t, env, "runaway guard fired", logStart, 25*time.Minute)
	t.Logf("runaway guard fired; checking member labels and comments")

	// Labels are applied inside fireRunawayGuard before the log line is written,
	// so by the time WaitForLogLine returns they should already be set. Allow a
	// generous 5-minute window for GitHub API propagation.
	for _, issueNum := range members {
		WaitForIssueLabel(t, env, env.RepoBeta, issueNum, "fabrik:paused", 5*time.Minute)
		WaitForIssueLabel(t, env, env.RepoBeta, issueNum, "fabrik:awaiting-input", 5*time.Minute)
		t.Logf("member #%d has fabrik:paused + fabrik:awaiting-input", issueNum)
	}

	// Assert the alert comment on at least one member (the first). The guard
	// posts it on every member unconditionally, so member[0] is sufficient.
	WaitForIssueComment(t, env, env.RepoBeta, members[0], "runaway guard tripped", 5*time.Minute)
	t.Logf("alert comment confirmed on member #%d", members[0])

	// No member should have reached Done.
	for _, issueNum := range members {
		if st := projectStatus(t, env, env.RepoBeta, issueNum); st == "Done" {
			t.Fatalf("member #%d reached Done — runaway guard did not fire in time", issueNum)
		} else {
			t.Logf("member #%d correctly not landed (status=%q)", issueNum, st)
		}
	}

	assertNoStaleTrainArtifacts(t, env, env.RepoBeta)
	t.Logf("runaway guard contract verified: all-poison batch → guard fires at cap → all Queued members paused → no member reaches Done")
}
