package gate

import (
	"os"
	"strings"
	"testing"
)

func readStream(t *testing.T, name string) []Event {
	t.Helper()
	events, err := readEventsFile("testdata/" + name)
	if err != nil {
		t.Fatal(err)
	}
	return events
}

func golden(t *testing.T, name string) string {
	t.Helper()
	data, err := os.ReadFile("testdata/" + name)
	if err != nil {
		t.Fatal(err)
	}
	return string(data)
}

// The goldens under testdata/ were generated by running the ORIGINAL bash
// report_test_outcomes / report_test_timings (jq + column -t) over the same
// recorded stream, so these assert byte-for-byte output parity with run.sh.
// The stream deliberately contains non-JSON lines, a truncated JSON line,
// subtests, a skip, a test that never got a slot, and a timed-out test whose
// last events are a panic dump (output events only).

func TestClassifyReportMatchesTheJqReport(t *testing.T) {
	got := Classify(readStream(t, "leg-stream.json")).Report() + "\n"
	if want := golden(t, "leg-stream.outcomes.golden"); got != want {
		t.Errorf("outcome report differs from the jq report\n got: %q\nwant: %q", got, want)
	}
}

func TestTimingsMatchTheColumnReport(t *testing.T) {
	got := "== per-test wall-clock (leg: pat/off), slowest first ==\n" + FormatTimings(Timings(readStream(t, "leg-stream.json")))
	if want := golden(t, "leg-stream.timings.golden"); got != want {
		t.Errorf("timing report differs from the jq|column report\n got: %q\nwant: %q", got, want)
	}
}

func TestClassifyBuckets(t *testing.T) {
	c := Classify(readStream(t, "leg-stream.json"))
	eq := func(name string, got []string, want ...string) {
		t.Helper()
		if strings.Join(got, ",") != strings.Join(want, ",") {
			t.Errorf("%s = %v, want %v", name, got, want)
		}
	}
	eq("pass", c.Pass, "TestCrossRepoSpawn", "TestSmokeSingleRepoDispatch")
	eq("fail", c.Fail, "TestNoWorkNeeded")
	eq("skip", c.Skip, "TestBlockedOnInput")
	// The test that timed out has only run/cont then output events; "output" is
	// excluded before taking the last action, so it lands in still-running
	// rather than vanishing.
	eq("running", c.Running, "TestMergeTrainHappyPath")
	eq("never started", c.NeverStarted, "TestNeverStarted")
}

func TestReportWithEmptyBucketsKeepsTheTrailingSpace(t *testing.T) {
	want := "completed - pass (0): \ncompleted - fail (0): \ncompleted - skip (0): \nstill running at kill time (0): \nnever started - queued behind -parallel cap (0): "
	if got := Classify(nil).Report(); got != want {
		t.Errorf("got %q", got)
	}
}

// Ported from hang_hardening_test.sh: last_completed_test_name.
func TestLastCompletedTest(t *testing.T) {
	parse := func(s string) []Event {
		ev, err := ReadEvents(strings.NewReader(s))
		if err != nil {
			t.Fatal(err)
		}
		return ev
	}
	cases := []struct {
		name, stream, want string
	}{
		{"an empty log reports (none yet)", "", "(none yet)"},
		{"the most recent terminal test; a still-running test is excluded", `{"Action":"run","Test":"TestAlpha"}
{"Action":"output","Test":"TestAlpha","Output":"=== RUN TestAlpha\n"}
{"Action":"pass","Test":"TestAlpha","Elapsed":1.2}
{"Action":"run","Test":"TestBeta"}
{"Action":"pause","Test":"TestBeta"}
{"Action":"cont","Test":"TestBeta"}
{"Action":"fail","Test":"TestBeta","Elapsed":3.4}
{"Action":"run","Test":"TestGamma"}
`, "TestBeta"},
		{"subtests are excluded", `{"Action":"pass","Test":"TestAlpha","Elapsed":1.0}
{"Action":"pass","Test":"TestAlpha/subcase","Elapsed":0.5}
`, "TestAlpha"},
		{"skip counts as a completion", `{"Action":"pass","Test":"TestAlpha","Elapsed":1.0}
{"Action":"skip","Test":"TestBeta","Elapsed":0.0}
`, "TestBeta"},
		{"non-JSON lines are skipped", "go: downloading x\n{\"Action\":\"pass\",\"Test\":\"TestA\"}\nnot json\n", "TestA"},
	}
	for _, c := range cases {
		if got := LastCompletedTest(parse(c.stream)); got != c.want {
			t.Errorf("%s: got %q, want %q", c.name, got, c.want)
		}
	}
}

func TestDecodeEventSkipsNonObjects(t *testing.T) {
	for _, line := range []string{"", "   ", "go: downloading", "123", `"str"`, "{truncated", "[1,2]"} {
		if _, ok := DecodeEvent(line); ok {
			t.Errorf("DecodeEvent(%q) should be skipped", line)
		}
	}
	if e, ok := DecodeEvent(`{"Action":"pass","Test":"TestA","Elapsed":1.5}`); !ok || e.Test != "TestA" || e.Elapsed != 1.5 {
		t.Errorf("got %+v %v", e, ok)
	}
}

func TestFormatTimingsAlignsLikeColumn(t *testing.T) {
	got := FormatTimings([]Timing{{"TestLong", "pass", 1234.5}, {"TestB", "fail", 3}, {"TestC", "skip", 0}})
	want := "1234.5s  pass  TestLong\n3s       fail  TestB\n0s       skip  TestC\n"
	if got != want {
		t.Errorf("got %q want %q", got, want)
	}
	if FormatTimings(nil) != "" {
		t.Error("an empty table prints nothing")
	}
}
